spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    url: jdbc:h2:mem:testdb
    
  jpa:
    properties:
      hibernate:
        format_sql : true
        show_sql : true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
server:
  port: 8082
  servlet:
    context-path: /contact
      
